name: Build
run-name: Build

on: 
  workflow_call:
      inputs:
          ref:
              description: >
                  The branch, tag or SHA to checkout. 
                  When checking out the repository that
                  triggered a workflow, this defaults 
                  to the reference or SHA for that event.
                  Otherwise, uses the default branch.
              required: false
              type: string
          app_name:
              description: The name of the build result.
              required: false
              default: appraiser-geo
              type: string
          linux_artifact_name:
              description: The name of the Linux build artifact.
              required: false
              default: AppraiserGeo-Linux
              type: string
          mac_artifact_name:
              description: The name of the MacOS build artifact.
              required: false
              default: AppraiserGeo-MacOS
              type: string
          win_artifact_name:
              description: The name of the Windows build artifact.
              required: false
              default: AppraiserGeo-Windows
              type: string
          retention_days:
              description: >
                The amount of days to keep the resulting build artifacts.
                Defaults to 7 days.
              required: false
              default: 7
              type: number

env:
  build-artifact-if-no-files-found: error

jobs:
  build-linux-app:
    runs-on: ubuntu-latest
    name: Build app for Linux
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run build
        run: pyinstaller src/main.py --onefile --noconfirm --name ${{ inputs.app_name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ inputs.linux_artifact_name }}
          path: dist/${{ inputs.app_name }}
          if-no-files-found: ${{ env.build-artifact-if-no-files-found }}
          retention-days: ${{ inputs.retention_days }}

  build-mac-app:
    runs-on: macos-latest
    name: Build app for Mac
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run build
        run: pyinstaller src/main.py --onefile --noconfirm --name ${{ inputs.app_name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ inputs.mac_artifact_name }}
          path: dist/${{ inputs.app_name }}
          if-no-files-found: ${{ env.build-artifact-if-no-files-found }}
          retention-days: ${{ inputs.retention_days }}

  build-mac-win:
    runs-on: windows-latest
    name: Build app for Windows
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run build
        run: pyinstaller src/main.py --onedir --noconfirm --name ${{ inputs.app_name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ inputs.win_artifact_name }}
          path: dist/${{ inputs.app_name }}
          if-no-files-found: ${{ env.build-artifact-if-no-files-found }}
          retention-days: ${{ inputs.retention_days }}
