name: Build app
run-name: Build app

on: 
  push:
    branches:
      - master

env:
  app-name: appraiser-geo
  build-artifact-if-no-files-found: error
  build-arfifact-retention-days: 7
  build-artifact-linux-name: AppraiserGeo-Linux
  build-artifact-macos-name: AppraiserGeo-MacOS
  build-artifact-windows-name: AppraiserGeo-Windows

jobs:
  build-linux-app:
    runs-on: ubuntu-latest
    name: Build app for Linux
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11.1
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Start build
        run: pyinstaller src/main.py --onefile --noconfirm --name ${{ env.app-name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ env.build-artifact-linux-name }}
          path: dist/${{ env.app-name }}
          if-no-files-found: ${{ env.build-artifact-if-no-files-found }}
          retention-days: ${{ env.build-arfifact-retention-days }}
  build-mac-app:
    runs-on: macos-latest
    name: Build app for Mac
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Start build
        run: pyinstaller src/main.py --onefile --noconfirm --name ${{ env.app-name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ env.build-artifact-macos-name }}
          path: dist/${{ env.app-name }}
          if-no-files-found: ${{ env.build-artifact-if-no-files-found }}
          retention-days: ${{ env.build-arfifact-retention-days }}

  build-mac-win:
    runs-on: windows-latest
    name: Build app for Windows
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11.1
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Start build
        run: pyinstaller src/main.py --onedir --noconfirm --name ${{ env.app-name }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ env.build-artifact-windows-name }}
          path: dist/${{ env.app-name }}.exe
          if-no-files-found: ${{ env.build-artifact-if-no-files-found }}
          retention-days: ${{ env.build-arfifact-retention-days }}
