name: Deploy
run-name: Deploy

on: 
  push:
    branches:
      - master

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        with: 
            ref: ${{ github.ref }}
    test:
        needs: lint
        uses: ./.github/workflows/test.yml
        with: 
            ref: ${{ github.ref }}
    docs:
        permissions:
            contents: read
            pages: write
            id-token: write
        needs: test
        uses: ./.github/workflows/publish-docs.yml
        with: 
            ref: ${{ github.ref }}
    build:
        needs: test
        uses: ./.github/workflows/build.yml
        with: 
            ref: ${{ github.ref }}