name: Lint
run-name: Lint

on: 
    workflow_call:
        inputs:
            ref:
                description: >
                    The branch, tag or SHA to checkout. 
                    When checking out the repository that
                    triggered a workflow, this defaults 
                    to the reference or SHA for that event.
                    Otherwise, uses the default branch.
                required: false
                type: string

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Lint source code
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}
            - name: Install Python
              uses: actions/setup-python@v5.1.1
              with:
                  python-version: 3.11
            - name: Install requirements
              run: pip install -r requirements.txt
            - name: Run linter
              id: run_linter
              run: pylint src