name: Publish docs
run-name: Publish docs

on: 
  push:
    branches:
      - master

jobs:
  checkout-source-code:
    runs-on: ubuntu-latest
    name: Check out source code
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Upload requirements
        uses: actions/upload-artifact@v4
        with:
          name: reqs
          path: requirements.txt
      - name: Upload Makefile
        uses: actions/upload-artifact@v4
        with:
          name: Makefile
          path: Makefile
  install-python:
    runs-on: ubuntu-latest
    name: Install Python
    steps:
      - uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11.1
  install-deps: 
    runs-on: ubuntu-latest
    name: Install dependencies
    needs: [install-python, checkout-source-code]
    steps:
      - name: Download requirements
        uses: actions/download-artifact@v4
        with:
          name: reqs
      - name: Install requirements
        run: pip install -r requirements.txt
  build-docs:
      runs-on: ubuntu-latest
      name: Build docs
      needs: install-deps
      steps:
        - name: Download Makefile
          uses: actions/download-artifact@v4
          with:
            name: Makefile
        - name: Building docs
          run: make html
        - name: Upload docs HTML
          uses: actions/upload-artifact@v4
          with:
            name: docs-html
            path: docs/build/html
  publish-doc-site:
    runs-on: ubuntu-latest
    name: Publish docs site
    needs: build-docs
    steps:
      # - name: Download docs HTML
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: docs-html
      - name: Publish docs HTML
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs-html
