name: Publish
run-name: Publish

on: 
  workflow_call:
      inputs:
          ref:
              description: >
                  The branch, tag or SHA to checkout. 
                  When checking out the repository that
                  triggered a workflow, this defaults 
                  to the reference or SHA for that event.
                  Otherwise, uses the default branch.
              required: false
              type: string

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Build docs
    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ inputs.ref }}
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11.1
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build docs
        run: make html
      - name: Upload docs HTML
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/build/html/

  publish-docs:
    runs-on: ubuntu-latest
    name: Publish docs site
    needs: build-docs
    steps:
      - name: Download docs HTML
        uses: actions/download-artifact@v4
        with:
          name: docs-html
          path: docs
      - name: Upload docs site artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: docs-site
          path: docs
      - name: Deploy docs site
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: docs-site
