name: Publish docs
run-name: Publish docs

on: 
  push:
    branches:
      - master

jobs:
  checkout-source-code:
    runs-on: ubuntu-latest
    name: Check out source code
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Upload requirements
        uses: actions/upload-artifact@v4
        with:
          name: reqs
          path: requirements.txt
      - name: Upload Makefile
        uses: actions/upload-artifact@v4
        with:
          name: Makefile
          path: Makefile
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/

  build-docs:
    runs-on: ubuntu-latest
    name: Build docs
    needs: checkout-source-code
    steps:
      - name: Install Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11.1
      - name: Download requirements
        uses: actions/download-artifact@v4
        with:
          name: reqs
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Download Makefile
        uses: actions/download-artifact@v4
        with:
          name: Makefile
      - name: Download docs source
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - name: Build docs
        run: make html
      - name: Upload docs HTML
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/build/html/

  publish-docs:
    runs-on: ubuntu-latest
    name: Publish docs site
    needs: build-docs
    permissions:
      contents: read
      pages: write
      id-token: write
    # environment:
    #   name: github-pages
    #   url: ${{ steps.docs-deployment.outputs.page_url }}
    steps:
      - name: Download docs HTML
        uses: actions/download-artifact@v4
        with:
          name: docs-html
          path: docs
      - run: ls -l docs
      # - name: Deploy docs site
      #   uses: actions/deploy-pages@v4.0.5
      #   with:
      #     artifact_name: docs-html
      
      # - name: Configure GitHub Pages
      #   uses: actions/configure-pages@v3
      # - name: Upload docs site artifact
      #   uses: actions/upload-pages-artifact@v3.0.1
      # - name: Deploy docs site
      #   id: docs-deployment
      #   uses: actions/deploy-pages@v1
