name: Publish docs
run-name: Publish docs

permissions:
  contents: read
  pages: write
  id-token: write

on: 
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    name: Publishing app's docs
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.11.1
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Build docs
        run: make html
      - name: Publish docs site
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: docs/build/html
