name: Scan Pull Request
run-name: Scan Pull Request

on: pull_request

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        with: 
            ref: ${{ github.ref }}
    test:
        needs: lint
        uses: ./.github/workflows/test.yml
        with: 
            ref: ${{ github.ref }}